#!/bin/bash
now=$(date +"%Y-%m-%d")
# Remove unused variables to speed up
export TERM=xterm; clear 2>/dev/null


#----- Auto Remove Vmess
data=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
for user in "${data[@]}"; do
    exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)
    [[ -z "$exp" ]] && continue
    d1=$(date -d "$exp" +%s 2>/dev/null)
    d2=$(date -d "$now" +%s)
    [[ -z "$d1" ]] && continue
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^## $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
        rm -rf /etc/vmess/$user
        rm -f /etc/kyt/limit/vmess/ip/$user
        rm -f /etc/limit/vmess/$user
        rm -f /var/www/html/vmess-$user.txt
        echo "Akun Vmess $user telah dihapus karena kadaluarsa pada $exp"
        
    fi
done

#----- Auto Remove Vless
data=($(cat /etc/xray/config.json | grep '^#&' | cut -d ' ' -f 2 | sort | uniq))
for user in "${data[@]}"; do
    exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)
    [[ -z "$exp" ]] && continue
    d1=$(date -d "$exp" +%s 2>/dev/null)
    d2=$(date -d "$now" +%s)
    [[ -z "$d1" ]] && continue
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#&& $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/vless/.vless.db
        rm -rf /etc/vless/$user
        rm -f /etc/kyt/limit/vless/ip/$user
        rm -f /etc/limit/vless/$user
        rm -f /var/www/html/vless-$user.txt
        echo "Akun Vless $user telah dihapus karena kadaluarsa pada $exp"
        
    fi
done

#----- Auto Remove Trojan
data=($(cat /etc/xray/config.json | grep '^#!' | cut -d ' ' -f 2 | sort | uniq))
for user in "${data[@]}"; do
    exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)
    [[ -z "$exp" ]] && continue
    d1=$(date -d "$exp" +%s 2>/dev/null)
    d2=$(date -d "$now" +%s)
    [[ -z "$d1" ]] && continue
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#!# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
        rm -rf /etc/trojan/$user
        rm -f /etc/kyt/trojan/ip/$user
        rm -f /etc/limit/trojan/$user
        rm -f /var/www/html/trojan-$user.txt
        echo "Akun Trojan $user telah dihapus karena kadaluarsa pada $exp"
        
    fi
done

#----- Auto Remove Shadowsocks
data=($(cat /etc/xray/config.json | grep '^#!!' | cut -d ' ' -f 2 | sort | uniq))
for user in "${data[@]}"; do
    exp=$(grep -w "^#!! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)
    [[ -z "$exp" ]] && continue
    d1=$(date -d "$exp" +%s 2>/dev/null)
    d2=$(date -d "$now" +%s)
    [[ -z "$d1" ]] && continue
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#!! $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#&! $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/shadowsocks/.shadowsocks.db
        rm -rf /etc/shadowsocks/$user
        rm -f /etc/kyt/shadowsocks/ip/$user
        rm -f /etc/limit/shadowsocks/$user
        rm -f /var/www/html/sodosokws-$user.txt
        echo "Akun Shadowsocks $user telah dihapus karena kadaluarsa pada $exp"
        
    fi
done

systemctl restart xray

##------ Auto Remove SSH (FIXED: Only UID >= 1000)
todaystime=$(date +%s)
# Get users from /etc/shadow that have an expiry date (field 8)
cat /etc/shadow | cut -d: -f1,8 | grep -v ":$" | while read line; do
    username=$(echo $line | cut -f1 -d:)
    userexp=$(echo $line | cut -f2 -d:)
    
    # Check if user is a normal user (UID >= 1000)
    user_uid=$(id -u "$username" 2>/dev/null)
    [[ -z "$user_uid" || $user_uid -lt 1000 || "$username" == "nobody" ]] && continue
    
    userexpireinseconds=$(($userexp * 86400))
    if [ $userexpireinseconds -le $todaystime ]; then
        userdel --force "$username" > /dev/null 2>&1
        sed -i "/^### $username/d" /etc/ssh/.ssh.db
        rm -f /etc/ssh/"$username"
        rm -f /etc/kyt/limit/ssh/ip/"$username"
        rm -f /var/www/html/ssh-"$username".txt
        exp_human=$(date -d @$userexpireinseconds +"%Y-%m-%d")
        echo "Akun SSH $username telah dihapus karena kadaluarsa pada $exp_human"
        
    fi
done

systemctl reload ssh
